import 'package:get/get.dart';

class MyLocale extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "ar": {
          "1": "جنة أكثر متعة إذا قمت بإنشاء حساب",
          "2": "إنشاء حساب",
          "3": "أو",
          "4": "لديك حساب ؟",
          "5": "سجل الدخول ",
          "6": "أسم المستخدم",
          "7": "كلمة المرور",
          "8": "تسجيل الدخول",
          "9": "نسيت كلمة المرور ؟",
          "10": "سجل الدخول بواسطة Apple",
          "11": "سجل الدخول بواسطة Google",
          "12": "سجل الدخول بواسطة Facebook",
          "13": "الاسم الاول",
          "14": "الاسم الاخير",
          "15": "اعد ادخال كلمة المرور",
          "16": "التسجيل",
          "17": "البريد الالكتروني",
          "18": "بالنقر على إنشاء حساب ، فإنك توافق على",
          "19": "شروط الخدمات وسياسة الخصوصية",
          "20": "الأماكن",
          "21": "ابحث عن أماكن",
          "22": "ترفيه ولعب",
          "23": "تعليم وابداع",
          "24": "رياضة ودفاع عن النفس",
          "25": "حيوانات أليفة",
          "26": "تسوق ومشتريات",
          "27": "أماكن خارجية وحدائق",
          "28": "أطعمة ومشروبات",
          "29": "دور ضيافة",
          "30": "حلاقين",
          "31": "تنسيق حفلات",
          "32": "الفعاليات",
          "33": "ابحث عن فعاليات",
          "34": "المفضلة",
          "35": "لا يوجد لديك مفضلة حتى الان",
          "36": "يمكنك التصفح الان والحفظ في مفضلتك",
          "37": "تصفح الان",
          "38": "مدينة",
          "39": "الكل",
          "40": "الرياض",
          "41": "الفلتر",
          "42": "إعادة ضبط",
          "43": "جدة",
          "44": "الدمام",
          "45": "مكه",
          "46": "أبها",
          "47": "نجران",
          "48": "حايل",
          "49": "نطاق الموعد",
          "50": "اليوم",
          "51": "هذا الاسبوع",
          "52": "هذا الشهر",
          "53": "نتيجة العرض",
          "54": "أكاديمية طويق",
          "55": "معسكر برمجة الروبوت للناشئين",
          "56":
              "ستتعلّم في هذه الدورة عن أساسيات البرمجة من خلال برمجة وابتكار الألعاب.",
          "57": "التاريخ :",
          "58": "٦ ابريل - ٢٠ ابريل",
          "59": "الوقت :",
          "60": "٣ - ٥ مساءً",
          "61":
              "الاتحاد السعودي للأمن السيبراني والبرمجة والدرونز ، جامعة الأميرة نورة",
          "62": "احجز الآن",
          "63": "عدد التذاكر",
          "64": "سعر التذكرة",
          "65": "الاجمالي",
          "66": "اختر طريقة الدفع",
          "67": "اتمام الدفع",
          "68":"ألحجز",
          "69":"فعالية سبتات للفتيات",
          "70":"ٌقدوة للتدريب",
          "71": "الرئيسية",
          "72": "الرياض",
          "73": "الطفولة عالم مخملي، مزدان بقلوب كالدر، وأرواح باذِخة الطهر" ,
          "74": "الأقرب إليك",
          "75": "الأجدد",
          "76": "الفعاليات القادمة",
          "77": "الفعاليات",
          "78": "شخصي",
          "79": "الاماكن",
          "80": "المفضلة",
          "81": "الانشطة",
          "82" : "رقم الجوال",
          "84" : "حفظ التغيرات ",
          "85" : "تغير اللغة"

        },
        "en": {
          "1": "JANNAH is more fun if you create an account",
          "2": "Create account",
          "3": "or",
          "4": "you already have account ?",
          "5": "Login",
          "6": "UserName",
          "7": "Password",
          "8": "Login",
          "9": "Forgot Password?",
          "10": "Sign in With Apple",
          "11": "sign in with Google",
          "12": "Sign in With Facebook",
          "13": "First Name",
          "14": "Last Name",
          "15": "Re-enter Password",
          "16": "SingUp",
          "17": "Email",
          "18": "By tapping “ Create Account”, you agree to",
          "19": "Terms of Services & Privacy Policy",
          "20": "Places",
          "21": "Search for places",
          "22": "Entertainment and play",
          "23": "Education and creativity",
          "24": "Sports and self-defense",
          "25": "Pets",
          "26": "Shopping and purchases",
          "27": "Outdoor spaces and gardens",
          "28": "Food and drinks",
          "29": "Guesthouse",
          "30": "Barbers",
          "31": "Party coordination",
          "32": "activities",
          "33": "Search for activities",
          "34": "Favorite",
          "35": "You didn't add any thing to your Favorite yet",
          "36": "you can now",
          "37": "Discover now",
          "38": "City",
          "39": "All",
          "40": "Riyadh",
          "41": "Filters",
          "42": "Reset",
          "43": "Jeddah",
          "44": "Dammam",
          "45": "Makkah",
          "46": "Abha",
          "47": "Najran",
          "48": "Hail",
          "49": "Date range",
          "50": "Today",
          "51": "This week",
          "52": "This month",
          "53": "Show Result",
          "54": "Tuwaiq Academy",
          "55": 'Junior Robot Programming Camp',
          "56":
              "In this course, you will learn about the basics\n of programming through programming and creating games.",
          "57": "Date :",
          "58": "April 6 - April 20",
          "59": "The time :",
          "60": "3-5 PM",
          "61":
              "Saudi Federation for Cybersecurity, Programming and Drones\n, Princess Noura University",
          "62": "Book Now",
          "63": "Tickets quntity",
          "64": "Ticket price",
          "65": "Total",
          "66": "Choose payment method",
          "67": "Complete Payment",
          "68":"Booking",
           "71": "Home",
          "72": "Riyadh",
          "73": "Childhood is a velvety world, adorned with Calder's hearts, and pure souls",
          "74": "closest to you",
          "75": " newest",
          "76": "Upcoming Events",
          "77": "activities",
          "78": "profile",
          "79": "places",
          "80": "Favorite",
          "81": "Events",
          "83" :"phone number",
          "84" : "Save changes",
          "85" : "change the language " ,
          
        }
      };
}
