// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUjbQu2TnDKzlQjap7G1e9mCGoWYzsaZ0',
    appId: '1:282640756278:web:fc5e7bb96742c9e123f297',
    messagingSenderId: '282640756278',
    projectId: 'finalproject-1cd77',
    authDomain: 'finalproject-1cd77.firebaseapp.com',
    storageBucket: 'finalproject-1cd77.appspot.com',
    measurementId: 'G-MFQCGT2PLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvWJ4t9eMrOdpc9sWfHDexmlblb3lYxL4',
    appId: '1:282640756278:android:05ba7da53050b86d23f297',
    messagingSenderId: '282640756278',
    projectId: 'finalproject-1cd77',
    storageBucket: 'finalproject-1cd77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT7Yb5mDiz5vv7K48QSABBUT6bg99CdSg',
    appId: '1:282640756278:ios:e2a9753af6fc009a23f297',
    messagingSenderId: '282640756278',
    projectId: 'finalproject-1cd77',
    storageBucket: 'finalproject-1cd77.appspot.com',
    iosClientId:
        '282640756278-t8gp3iivaa70ukm1rei5lim2lbm5rfm7.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT7Yb5mDiz5vv7K48QSABBUT6bg99CdSg',
    appId: '1:282640756278:ios:e2a9753af6fc009a23f297',
    messagingSenderId: '282640756278',
    projectId: 'finalproject-1cd77',
    storageBucket: 'finalproject-1cd77.appspot.com',
    iosClientId:
        '282640756278-t8gp3iivaa70ukm1rei5lim2lbm5rfm7.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );
}
